---
title: "Massachusetts Premature Mortality Analysis"
author: "Rachel Nethery"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: pdf_document
classoption: landscape
---

```{r loadlibs,include=FALSE}
library(maptools)
library(spdep)
library(MASS)
library(msm)
library(tigris)
options(tigris_use_cache = FALSE)
library(CARBayes)
library(knitr)
library(kableExtra)
library(lme4)
library(xtable)
library(reshape2)

blank_lines <- function(n = 10){cat(rep("&nbsp;  ",n), sep="\n")}
```

```{r setup_rs, include=FALSE,cache=TRUE}

## setup for race-stratified models ##

## number of burn-in samples to collect ##
nburn<-20000
## number of burn-in + post samples ##
nsamp<-30000

set.seed(2)


#############################
## read in the merged data ##
#############################

load('merged_pmrates_ce_acs_wp_strat.RData')

########################################
## adjacency matrix for census tracts ##
########################################

## extract shapefile ##
ma_shp<-tracts(state = 'MA',year=2010)

## get adjacency matrix ##
foo = poly2nb(ma_shp, queen=TRUE, row.names=ma_shp@data$GEOID10)

## create function to process data, apply CAR models, and output results ##
apply_car_rs<-function(x){
  
  x<-x[which(!(x$race %in% c('total','hispanic'))),]
  
  ## add numeric black/white indicator ##
  x$bw_ind<-0
  x$bw_ind[which(x$race=='black')]<-1
  
  ## remove CTs with 0 population (either ACS or WP) ##
  x<-subset(x,acs_1yr_pop>0 & wp_1yr_pop>0)
  
  ## remove missing covariates ##
  x<-x[complete.cases(x[,c('bw_ind','acs_pov_pct')]),]
  
  x$acs_pov_pct<-as.numeric(scale(x$acs_pov_pct))
  
  ## sort by geoid ##
  x<-x[order(x$GEOID),]
  
  N<-nrow(x)
  Nct<-length(unique(x$GEOID))
  
  #######################################################################
  ## align ordering of adjacency matrix and covariates/population data ##
  #######################################################################
  
  W=nb2mat(foo,style='B')
  
  ## census tracts in W with matches in the data ##
  tractrm<-which(rownames(W) %in% as.character(x$GEOID))
  
  W<-W[tractrm,tractrm]
  
  W<-W[order(as.numeric(rownames(W))),order(as.numeric(rownames(W)))]
  
  identical(unique(as.character(x$GEOID)),rownames(W))
  
  ####################################################
  ## fit CAR models with census/acs/wp denominators ##
  ####################################################
  
  x$ind.area<-as.numeric(as.factor(x$GEOID))
  x$ind.re<-as.factor(1:N)
  

  car_offs1<-S.CARmultilevel(ndeaths_1yr~bw_ind+acs_pov_pct+offset(log(acs_1yr_istexp)),family="poisson",data=x,
                             ind.area=x$ind.area,
                             ind.re=x$ind.re,
                             W=W,burnin=nburn,n.sample=nsamp)
  
  car_offs2<-S.CARmultilevel(ndeaths_1yr~bw_ind+acs_pov_pct+offset(log(wp_1yr_istexp)),family="poisson",data=x,
                             ind.area=x$ind.area,
                             ind.re=x$ind.re,
                             W=W,burnin=nburn,n.sample=nsamp)
      
  car_offs3<-S.CARmultilevel(ndeaths_1yr~bw_ind+acs_pov_pct+offset(log(ce_1yr_istexp)),family="poisson",data=x,
                             ind.area=x$ind.area,
                             ind.re=x$ind.re,
                             W=W,burnin=nburn,n.sample=nsamp)
    
    
    sum_bw<-as.data.frame(round(cbind(exp(car_offs1[[1]][1:3,1:3]),exp(car_offs2[[1]][1:3,1:3]),exp(car_offs3[[1]][1:3,1:3])),2))
    names(sum_bw)<-rep(c('IRR','Lower CL','Upper CL'),3)
    #rownames(sum_bw)<-c('Intercept','Black (vs NH-White)','Poverty')
    
    return(sum_bw)
}

out_car_rs<-lapply(adat,apply_car_rs)

 
```

# 1. Race-stratified models
&nbsp;
&nbsp;

```{r output_rs, echo=FALSE,results='asis'}

## make a table of race-stratified results and print ##

## collapse point estimates and CIs in the tables ##
out_list_rs<-lapply(out_car_rs, FUN=function(x) data.frame('ACS'=paste(x[,1],paste0('(',apply( x[ ,2:3] , 1 , paste0 , collapse = "," ),')')),
                                                            'WP'=paste(x[,4],paste0('(',apply( x[ ,5:6] , 1 , paste0 , collapse = "," ),')')),
                                                            'Census'=paste(x[,7],paste0('(',apply( x[ ,8:9] , 1 , paste0 , collapse = "," ),')'))))

out_tab_rs<-data.frame('parameter'=rep(c('Intercept','Race','Poverty'),3),rbind(out_list_rs[[1]],out_list_rs[[2]],out_list_rs[[3]]))
rownames(out_tab_rs)<-paste0(rep(2008:2010,each=3),rep(c('a','b','c'),3))

capture.output(xtable(out_tab_rs),file='rs_table.txt')

xtable(out_tab_rs)

```

```{r setup_agg,include=F,cache=T}

## setup for CT-aggregate models ##

## function to process data, apply CAR models, and output results ##
apply_car_agg<-function(x,x_2010){
  
  ## extract number of whites per CT ##
  n_black<-dcast(subset(x_2010,race=='black' | race=='total',select=c('GEOID','race','acs_1yr_pop')),GEOID~race)
  n_black$black_pct<-n_black$black/n_black$total
  
  #rm_geo<-subset(x,(race=='black' | race=='white') & 
  #                        (acs_1yr_pop==0 | wp_1yr_pop==0),select='GEOID')[,1]
  
  x<-subset(x,race=='total')# & !(GEOID %in% rm_geo))
  x<-merge(x,n_black,by='GEOID')

  ## remove CTs with 0 population (either ACS or WP) ##
  x<-subset(x,acs_1yr_pop>0 & wp_1yr_pop>0)
  
  ## remove missing covariates ##
  x<-x[complete.cases(x[,c('black_pct','acs_pov_pct')]),]
  
  x$acs_pov_pct<-as.numeric(scale(x$acs_pov_pct/100))
  x$black_pct<-as.numeric(scale(x$black_pct))
  
  ## sort by geoid ##
  x<-x[order(x$GEOID),]
  
  N<-nrow(x)
  Nct<-length(unique(x$GEOID))
  
  #######################################################################
  ## align ordering of adjacency matrix and covariates/population data ##
  #######################################################################
  
  W=nb2mat(foo,style='B')
  
  ## census tracts in W with matches in the data ##
  tractrm<-which(rownames(W) %in% as.character(x$GEOID))
  
  W<-W[tractrm,tractrm]
  
  W<-W[order(as.numeric(rownames(W))),order(as.numeric(rownames(W)))]
  
  identical(unique(as.character(x$GEOID)),rownames(W))
  
  ####################################################
  ## fit CAR models with census/acs/dp denominators ##
  ####################################################
  
  car_offs1<-S.CARbym(ndeaths_1yr~black_pct+acs_pov_pct+offset(log(acs_1yr_istexp)),family="poisson",data=x,
                             W=W,burnin=nburn,n.sample=nsamp)
  
  car_offs2<-S.CARbym(ndeaths_1yr~black_pct+acs_pov_pct+offset(log(wp_1yr_istexp)),family="poisson",data=x,
                             W=W,burnin=nburn,n.sample=nsamp)
      
  car_offs3<-S.CARbym(ndeaths_1yr~black_pct+acs_pov_pct+offset(log(ce_1yr_istexp)),family="poisson",data=x,
                             W=W,burnin=nburn,n.sample=nsamp)
    
    
    sum_bw<-as.data.frame(round(cbind(exp(car_offs1[[1]][1:3,1:3]),exp(car_offs2[[1]][1:3,1:3]),exp(car_offs3[[1]][1:3,1:3])),2))
    names(sum_bw)<-rep(c('IRR','Lower CL','Upper CL'),3)
    #rownames(sum_bw)<-c('Intercept','Race','Poverty')
    
    return(sum_bw)
}

out_car_agg<-lapply(adat,apply_car_agg,x_2010=adat[[length(adat)]])

```

# 2. CT-aggregate models
&nbsp;
&nbsp;

```{r output_agg, echo=FALSE,results='asis'}

## make a table of CT-aggregate results and print ##

## collapse point estimates and CIs in the tables ##
out_list_agg<-lapply(out_car_agg, FUN=function(x) data.frame('ACS'=paste(x[,1],paste0('(',apply( x[ ,2:3] , 1 , paste0 , collapse = "," ),')')),
                                                            'WP'=paste(x[,4],paste0('(',apply( x[ ,5:6] , 1 , paste0 , collapse = "," ),')')),
                                                            'Census'=paste(x[,7],paste0('(',apply( x[ ,8:9] , 1 , paste0 , collapse = "," ),')'))))

out_tab_agg<-data.frame('parameter'=rep(c('Intercept','Race','Poverty'),3),rbind(out_list_agg[[1]],out_list_agg[[2]],out_list_agg[[3]]))
rownames(out_tab_agg)<-paste0(rep(2008:2010,each=3),rep(c('a','b','c'),3))

capture.output(xtable(out_tab_agg),file='agg_table.txt')

xtable(out_tab_agg)

```

# 3. Combined table
&nbsp;
&nbsp;

```{r combine_rs_agg,echo=FALSE,results='asis'}

capture.output(xtable(cbind(out_tab_agg,out_tab_rs[,-1])),file='combined_table.txt')

xtable(cbind(out_tab_agg,out_tab_rs[,-1]))

```
